const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const translations = {
  ru: {
    'logo.main': 'Эндоскопия',
    'logo.accent': 'простыми словами',
    'nav.about': 'О враче',
    'nav.services': 'Услуги',
    'nav.diplomas': 'Дипломы',
    'nav.reviews': 'Отзывы',
    'nav.contacts': 'Контакты',
    'nav.appointment': 'Записаться на прием',
    'nav.blog': 'Блог',
    'nav.topics': 'Темы',
    'nav.ask': 'Задать вопрос',
    'hero.badge.blog': 'Образовательный blog врача Олега Тетерника',
    'hero.title.main': 'Эндоскопия',
    'hero.title.accent': 'простыми словами',
    'hero.specialization': 'Рассказываю про гастроскопию, колоноскопию, подготовку и лечение без мифов и лишнего страха. Советы врача-эндоскописта, хирурга, врача УЗИ с 8-летним опытом.',
    'hero.experience.number': '8',
    'hero.experience.label': 'Лет профессионального\nопыта в медицине',
    'hero.btn.blog': 'Читать блог',
    'hero.btn.ask': 'Задать вопрос',
    'hero.float.value': '5000+',
    'hero.float.label': 'Довольных пациентов',
    'hero.scroll': 'Листайте вниз',
    'stats.exp.label': 'Лет опыта',
    'stats.exp.sub': 'в эндоскопии и медицине',
    'stats.patients.label': 'Процедур в год',
    'stats.patients.sub': 'более 3000 исследований',
    'stats.patients.live': 'Ежегодно',
    'stats.spec.number': 'Эндоскопист',
    'stats.spec.label': 'Специализация',
    'stats.spec.sub': 'диагностическая и лечебная эндоскопия',
    'section.stats': 'Цифры доверия',
    'section.about': 'О враче',
    'section.services': 'Услуги',
    'section.diplomas': 'Дипломы и сертификаты',
    'section.reviews': 'Отзывы пациентов',
    'section.contacts': 'Контакты',
    'about.subtitle': 'Знакомство с врачом',
    'about.title': 'Тетерник Олег Александрович',
    'about.role': 'Врач Хирург Эндоскопист',
    'about.bio.1': 'Профессионал с 8-летним опытом в проведении высокоточных эндоскопических и хирургических вмешательств. Основной приоритет — максимальная безопасность, безболезненность и комфорт пациента во время каждой процедуры.',
    'about.bio.2': 'Благодаря современному оборудованию и индивидуальному подходу, мы обеспечиваем точную диагностику и эффективное лечение заболеваний желудочно-кишечного тракта.',
    'about.spec.1': 'Гастроскопия',
    'about.spec.2': 'Колоноскопия',
    'about.spec.3': 'ЭРХПГ',
    'about.spec.4': 'Бронхоскопия',
    'about.spec.5': 'УЗИ',
    'about.spec.6': 'Хирургия',
    'about.card.location.label': 'Место приема',
    'about.card.location.value': '17 больница, г.Харьков, пр.Героев Харькова 195',
    'about.card.phone.label': 'Телефон',
    'about.btn': 'Записаться на прием',
    'services.subtitle': 'Направления и исследования',
    'services.title': 'Медицинские услуги',
    'services.card.btn': 'Подробнее о процедуре',
    'services.modal.close': 'Закрыть',
    'services.modal.appointment': 'Записаться на прием',
    'services.modal.steps_title': 'Пошаговый процесс процедуры',
    'appointment.modal.title': 'Запись на прием',
    'appointment.modal.subtitle': 'Заполните форму на сайте или воспользуйтесь Telegram-ботом',
    'appointment.form.name.label': 'Ваше имя (ФИО)',
    'appointment.form.name.placeholder': 'Иванов Иван Иванович',
    'appointment.form.phone.label': 'Номер телефона',
    'appointment.form.phone.placeholder': '+380XXXXXXXXX',
    'appointment.form.service.label': 'Выберите услугу',
    'appointment.form.comment.label': 'Краткий комментарий / симптомы (опционально)',
    'appointment.form.comment.placeholder': 'Опишите, что вас беспокоит или желаемое время...',
    'appointment.form.submit': 'Отправить заявку',
    'appointment.divider': 'или заполните онлайн-форму',
    'appointment.tg.btn': 'Записаться через Telegram-бот',
    'appointment.success.title': 'Спасибо! Заявка принята',
    'appointment.success.desc': 'Мы перезвоним вам в ближайшее время для подтверждения времени приема.',
    'appointment.success.btn': 'Понятно',
    'contacts.subtitle': 'Локация и связь',
    'contacts.title': 'Контактная информация',
    'contacts.address.label': 'Место приема',
    'contacts.address.value': '17-я городская больница, г. Харьков, пр. Героев Харькова 195',
    'contacts.schedule.label': 'График приема',
    'contacts.schedule.value': 'Пн – Сб: 08:00 – 15:00',
    'contacts.schedule.sub': 'Воскресенье: выходной',
    'contacts.phone.label': 'Телефон для записи',
    'contacts.instagram.label': 'Официальный Instagram',
    'contacts.navigation.title': 'Как найти корпус хирургии?',
    'contacts.navigation.desc': 'Смотрите пошаговую видеоинструкцию в сохраненных Историях Instagram',
    'contacts.navigation.btn': 'Посмотреть маршрут',
    'contacts.map.btn': 'Открыть в Google Maps',
    'contacts.appointment.btn': 'Записаться на прием',
    'reviews.subtitle': 'Доверие и реальный опыт',
    'reviews.title': 'Отзывы пациентов',
    'reviews.btn.leave': 'Оставить отзыв',
    'reviews.rating.count': 'на основе отзывов пациентов',
    'reviews.loading': 'Загрузка отзывов...',
    'reviews.empty': 'Пока нет опубликованных отзывов. Будьте первым!',
    'reviews.modal.title': 'Ваш отзыв о приеме',
    'reviews.modal.subtitle': 'Поделитесь вашими впечатлениями от процедуры или консультации',
    'reviews.modal.name.label': 'Ваше имя (ФИО)',
    'reviews.modal.name.placeholder': 'Елена Мельник',
    'reviews.modal.stars.label': 'Ваша оценка',
    'reviews.modal.text.label': 'Текст отзыва',
    'reviews.modal.text.placeholder': 'Напишите ваши впечатления от визита, отношение врача...',
    'reviews.modal.submit': 'Отправить отзыв',
    'reviews.success.title': 'Спасибо за ваш отзыв!',
    'reviews.success.desc': 'Ваш отзыв успешно сохранен и будет опубликован после модерации.',
    'exhibits.esge.city': 'г. Милан, Италия',
    'exhibits.esge.title': 'ESGE Days 2026',
    'exhibits.esge.desc': 'Международная эндоскопическая конференция. Обмен опытом с ведущими европейскими специалистами, обсуждение новейших стандартов и технологий в оперативной эндоскопии.',
    'exhibits.kiev.city': 'г. Киев, Украина',
    'exhibits.kiev.title': 'KievEndo 2023',
    'exhibits.kiev.desc': 'Научно-практическая конференция. Презентация клинических случаев, обсуждение современных методик малоинвазивной хирургии и диагностической эндоскопии в Украине.',
    'footer.copy': '© 2026 Тетерник О.О. Все права защищены.',
    'topics.more': 'Узнать больше',
    'topics.less': 'Свернуть',
    'topics.gastro.label': 'Гастроскопия',
    'topics.gastro.sublabel': 'Подготовка, процесс, результаты',
    'topics.gastro.q1': 'Что это такое?',
    'topics.gastro.a1': 'Это осмотр слизистой оболочки пищевода, желудка и двенадцатиперстной кишки с помощью гибкого тонкого зонда с видеокамерой.',
    'topics.gastro.q2': 'Когда стоит пройти?',
    'topics.gastro.li1': 'Частая изжога, отрыжка, горечь во рту',
    'topics.gastro.li2': 'Боль в верхней части живота (натощак или после еды)',
    'topics.gastro.li3': 'Длительная тошнота или проблемы с глотанием',
    'topics.gastro.q3': 'Как подготовиться?',
    'topics.gastro.a3': 'Процедура проводится исключительно <strong>натощак</strong>. Последний прием пищи — минимум за 8-10 часов до исследования. Воду нельзя пить за 3-4 часа до процедуры.',
    'topics.gastro.btn': 'Детальнее про Гастроскопию',
    'topics.gastro.posts_btn': 'Статьи о Гастроскопии',
    'topics.colono.label': 'Колоноскопия',
    'topics.colono.sublabel': 'Как не бояться и подготовиться',
    'topics.colono.q1': 'Почему это жизненно важно?',
    'topics.colono.a1': 'Это золотой стандарт профилактики рака толстой кишки. Позволяет обнаружить и сразу удалить полипы (доброкачественные новообразования) до того, как они станут опасными.',
    'topics.colono.q2': 'Больно ли это?',
    'topics.colono.a2': 'Современная колоноскопия в 95% случаев проводится <strong>в состоянии медикаментозного сна (седации)</strong>. Вы просто спите 15-20 минут и не чувствуете никакого дискомфорта.',
    'topics.colono.q3': 'Главное в подготовке:',
    'topics.colono.a3': 'Качество осмотра на 90% зависит от чистоты кишечника. Необходимо за 3 дня соблюдать бесшлаковую диету и накануне выпить специальный очищающий раствор по схеме.',
    'topics.colono.btn': 'Детальнее про Колоноскопию',
    'topics.colono.posts_btn': 'Статьи о Колоноскопии',
    'topics.usg.label': 'УЗИ и хирургия',
    'topics.usg.sublabel': 'Когда и зачем нужны',
    'topics.usg.q1': 'УЗИ диагностика',
    'topics.usg.a1': 'Быстрый и безопасный метод проверить состояние внутренних органов (печени, желчного пузыря, поджелудочной железы, почек) без облучения.',
    'topics.usg.q2': 'Оперативная эндоскопия',
    'topics.usg.a2': 'Это хирургия без разрезов. Благодаря эндоскопу врач может удалить инородные тела, остановить внутреннее кровотечение или выполнить полипэктомию (удаление полипов желудка или кишечника) непосредственно во время осмотра.',
    'topics.usg.q3': 'Преимущества:',
    'topics.usg.a3': 'Пациент восстанавливается уже через несколько часов после вмешательства и может возвращаться к обычной жизни.',
    'topics.usg.btn1': 'Детальнее про УЗИ',
    'topics.usg.posts_btn1': 'Статьи об УЗИ',
    'topics.usg.btn2': 'Детальнее про Хирургию',
    'topics.usg.posts_btn2': 'Статьи о Хирургии',
    'blog.subtitle': 'Экспертные материалы',
    'blog.title': 'Блог об эндоскопии',
    'blog.desc': 'Врач-эндоскопист Тетерник О.О. рассказывает о процедурах, развенчивает мифы и делится полезными советами по подготовке к эндоскопии.',
    'blog.empty': 'Посты еще не опубликованы.',
    'diplomas.subtitle': 'Образование и достижения',
    'diplomas.title': 'Дипломы и сертификаты',
    'diplomas.tab.education': 'Образование',
    'diplomas.tab.certificates': 'Сертификаты',
    'diplomas.tab.exhibitions': 'Конференции и выставки',

    // Нові ключі для сторінок послуг
    'service.back': 'Назад на главную',
    'appointment.form.btn_redirect': 'Заполнить форму на сайте',
'service.gastro.meta.title': 'Гастроскопия | Врач Тетерник О.А.',
    'service.gastro.title': 'Гастроскопия',
    'service.gastro.subtitle': 'Современное эндоскопическое исследование желудка без мифов, боли и страха.',
    'service.gastro.btn': 'Записаться на гастроскопию',
    'service.gastro.toc.title': 'Путеводитель по вопросам подготовки:',
    'service.gastro.toc.item1': '1. Почему правильная подготовка важна?',
    'service.gastro.toc.item2': '2. Рекомендации за 1 день до обследования',
    'service.gastro.toc.item3': '3. Что делать в день гастроскопии?',
    'service.gastro.toc.item4': '4. Если вы постоянно принимаете лекарства',
    'service.gastro.toc.item5': '5. Если гастроскопия под седацией (во сне)',
    'service.gastro.toc.item6': '6. Что взять с собой и как одеться?',
    'service.gastro.why.title': '1. Почему правильная подготовка важна?',
    'service.gastro.why.p1': '<strong>Гастроскопия (ВГДС)</strong> — это точный метод обследования пищевода, желудка и двенадцатиперстной кишки. Чтобы врач смог детально осмотреть слизистую оболочку, выявить даже мелкие воспаления, язвы, полипы или ранние формы рака, желудок должен быть абсолютно пустым.',
    'service.gastro.why.p2': 'Даже небольшое количество пищи или жидкости в желудке может значительно ухудшить обзор слизистой оболочки, увеличить риск возникновения рвотного рефлекса во время процедуры и усложнить точную диагностику.',
    'service.gastro.diet1.title': '2. Рекомендации за 1 день до обследования',
    'service.gastro.diet1.li1': 'Питайтесь в обычном режиме, но избегайте переедания и тяжелой пищи.',
    'service.gastro.diet1.li2': 'Последний легкий прием пищи — не позднее <strong>19:00–20:00</strong> (если исследование запланировано на утро).',
    'service.gastro.diet1.li3': 'Категорически не употребляйте алкоголь накануне процедуры.',
    'service.gastro.day.title': '3. Что делать в день гастроскопии?',
    'service.gastro.day.morning_title': 'Если обследование утром:',
    'service.gastro.day.morning_li1': 'Не ешьте как минимум <strong>6–8 часов</strong> до процедуры.',
    'service.gastro.day.morning_li2': 'Не пейте молоко, кофе, соки или газированные напитки.',
    'service.gastro.day.morning_li3': 'Чистую негазированную воду можно пить небольшими глотками не позднее чем за <strong>2 часа</strong> до начала процедуры.',
    'service.gastro.day.afternoon_title': 'Если гастроскопия после обеда:',
    'service.gastro.day.afternoon_p': 'Разрешается легкий завтрак не позднее чем за <strong>6–8 часов</strong> до обследования. Любой дальнейший прием пищи после этого строго запрещен.',
    'service.gastro.med.title': '4. Если вы постоянно принимаете лекарства',
    'service.gastro.med.li1': 'Препараты от артериального давления и большинства сердечных заболеваний можно принять утром в обычном режиме, запив минимальным количеством чистой воды.',
    'service.gastro.med.li2': 'Если вы принимаете инсулин, сахароснижающие препараты или средства, разжижающие кровь (антикоагулянты), обязательно сообщите об этом врачу заранее.',
    'service.gastro.med.li3': 'Может потребоваться временная коррекция схемы приема или отмена некоторых лекарств по согласованию с врачом.',
    'service.gastro.sedation.title': '5. Если гастроскопия проводится под седацией (во сне)',
    'service.gastro.sedation.li1': 'Не ешьте как минимум <strong>6–8 часов</strong> до начала процедуры.',
    'service.gastro.sedation.li2': 'Не пейте никакой жидкости в течение последних <strong>2 часов</strong> до процедуры.',
    'service.gastro.sedation.li3': 'Внимание! После седации категорически запрещено управлять автомобилем в течение суток. Пожалуйста, заранее позаботьтесь о сопровождении домой.',
    'service.gastro.before.title': '6. Что взять с собой и как одеться?',
    'service.gastro.before.li1': 'Возьмите с собой результаты предыдущих гастроскопий, биопсий и других медицинских обследований (при наличии), чтобы врач мог оценить динамику.',
    'service.gastro.before.li2': 'Если вы носите съемные зубные протезы — их необходимо будет снять непосредственно перед исследованием.',
    'service.gastro.before.li3': 'Наденьте удобную, свободную одежду, которая не сдавливает шею, грудную клетку и живот.',

'service.colono.meta.title': 'Колоноскопия | Врач Тетерник О.А.',
    'service.colono.title': 'Колоноскопия (видеоколоноскопия)',
    'service.colono.subtitle': 'Эффективное обследование толстого кишечника в состоянии медикаментозного сна.',
    'service.colono.btn': 'Записаться на колоноскопию',
    'service.colono.toc.title': 'Путеводитель по вопросам подготовки:',
    'service.colono.toc.item1': '1. Почему колоноскопия важна и что это такое?',
    'service.colono.toc.item2': '2. Бесшлаковая диета за 3 дня до обследования',
    'service.colono.toc.item3': '3. Что можно есть и пить накануне?',
    'service.colono.toc.item4': '4. Схема приема препарата Изиклин (двухэтапная)',
    'service.colono.toc.item5': '5. Важные рекомендации при подготовке',
    'service.colono.toc.item6': '6. Видеоинструкция по подготовке',
    'service.colono.why.title': '1. Почему колоноскопия важна и что это такое?',
    'service.colono.why.p1': '<strong>Видеоколоноскопия (ФКС)</strong> — это высокоточный эндоскопический метод исследования, позволяющий врачу детально осмотреть слизистую оболочку толстой кишки изнутри с помощью специального гибкого зонда (колоноскопа).',
    'service.colono.why.p2': 'Хорошо очищенный кишечник позволяет врачу внимательно осмотреть слизистую оболочку, выявить даже небольшие полипы или ранние формы рака толстой кишки и, при необходимости, сразу их удалить. Качественная подготовка значительно повышает точность колоноскопии и может избавить от необходимости повторного обследования.',
    'service.colono.diet3.title': '2. Бесшлаковая диета за 3 дня до обследования',
    'service.colono.diet3.p1': 'За 3 дня до колоноскопии рекомендуется перейти на бесшлаковую диету.',
    'service.colono.diet3.allowed_title': 'Можно употреблять:',
    'service.colono.diet3.allowed_li1': 'отварное мясо и рыбу;',
    'service.colono.diet3.allowed_li2': 'яйца;',
    'service.colono.diet3.allowed_li3': 'белый хлеб или тосты;',
    'service.colono.diet3.allowed_li4': 'рис, манную кашу;',
    'service.colono.diet3.allowed_li5': 'кисломолочные продукты без добавок;',
    'service.colono.diet3.allowed_li6': 'прозрачные бульоны.',
    'service.colono.diet3.forbidden_title': 'Нельзя:',
    'service.colono.diet3.forbidden_li1': 'овощи и фрукты;',
    'service.colono.diet3.forbidden_li2': 'ягоды;',
    'service.colono.diet3.forbidden_li3': 'зелень, грибы, орехи;',
    'service.colono.diet3.forbidden_li4': 'семена, бобовые;',
    'service.colono.diet3.forbidden_li5': 'черный хлеб;',
    'service.colono.diet3.forbidden_li6': 'каши из цельного зерна.',
    'service.colono.diet1.title': '3. Что можно есть и пить накануне?',
    'service.colono.diet1.allowed_title': 'Разрешаются только прозрачные жидкости:',
    'service.colono.diet1.allowed_li1': 'вода, некрепкий чай;',
    'service.colono.diet1.allowed_li2': 'прозрачный бульон;',
    'service.colono.diet1.allowed_li3': 'яблочный сок без мякоти;',
    'service.colono.diet1.allowed_li4': 'прозрачные спортивные напитки.',
    'service.colono.diet1.forbidden_p': 'Молоко, кефир, соки с мякотью и алкоголь употреблять нельзя.',
    'service.colono.prep.title': '4. Схема приема препарата Изиклин',
    'service.colono.prep.p1': 'Наилучший результат обеспечивает двухэтапная (split-dose) схема подготовки.',
    'service.colono.prep.morning_title': 'Если колоноскопия назначена на утро',
    'service.colono.prep.morning_li1': '<strong>Вечером накануне (18:00–20:00):</strong> выпейте первую дозу Изиклина согласно инструкции, после чего выпейте примерно 1 литр прозрачной жидкости.',
    'service.colono.prep.morning_li2': '<strong>Утром в день обследования (за 4–5 часов до процедуры):</strong> примите вторую дозу препарата, после чего снова выпейте 1 литр прозрачной жидкости.',
    'service.colono.prep.morning_p': 'Все жидкости необходимо закончить принимать не позднее чем за 2 часа до седации или процедуры (если врач не дал других рекомендаций).',
    'service.colono.prep.afternoon_title': 'Если колоноскопия после обеда',
    'service.colono.prep.afternoon_p': 'Первую дозу можно принять утром, а вторую — через несколько часов, следуя детальным рекомендациям вашего врача.',
    'service.colono.tips.title': '5. Важные рекомендации при подготовке',
    'service.colono.tips.li1': 'Во время подготовки пейте достаточное количество жидкости, чтобы избежать обезвоживания.',
    'service.colono.tips.li2': 'Если вы постоянно принимаете препараты для разжижения крови, сахароснижающие средства или инсулин, обязательно сообщите об этом врачу заранее.',
    'service.colono.tips.li3': 'При сильной тошноте или рвоте обратитесь к медицинскому персоналу.',
    'service.colono.video.title': '6. Видеоинструкция по подготовке',
    'service.colono.video.desc': 'Посмотрите подробное видео о том, как правильно подготовиться к эндоскопическому исследованию:',

'service.uzd.meta.title': 'УЗИ (ультразвуковая диагностика) | Врач Тетерник О.А.',
    'service.uzd.title': 'УЗИ (Ультразвуковая диагностика)',
    'service.uzd.subtitle': 'Безопасный, безболезненный и точный метод оценки внутренних органов.',
    'service.uzd.btn': 'Записаться на УЗИ',
    'service.uzd.toc.title': 'Путеводитель по вопросам подготовки и проведения:',
    'service.uzd.toc.item1': '1. Что такое УЗИ и как оно работает?',
    'service.uzd.toc.item2': '2. Какие органы можно обследовать с помощью УЗИ?',
    'service.uzd.toc.item3': '3. Как правильно подготовиться к УЗИ брюшной полости?',
    'service.uzd.toc.item4': '4. Подготовка к УЗИ почек и мочевого пузыря',
    'service.uzd.toc.item5': '5. Какие преимущества УЗИ и когда оно необходимо?',
    'service.uzd.about.title': '1. Что такое УЗИ и как оно работает?',
    'service.uzd.about.p1': '<strong>Ультразвуковая диагностика (УЗИ)</strong> — это неинвазивный, быстрый и полностью безопасный метод исследования. Он основан на использовании высокочастотных звуковых волн, которые отражаются от тканей организма и формируют четкое изображение внутренних органов на экране сканера в реальном времени.',
    'service.uzd.about.p2': 'Поскольку УЗИ не использует ионизирующее (рентгеновское) излучение, оно абсолютно безвредно. Обследование можно проводить многократно пациентам любого возраста, в том числе детям и беременным женщинам, для оценки формы, размеров, структуры органов и кровотока в них.',
    'service.uzd.organs.title': '2. Какие органы можно обследовать с помощью УЗИ?',
    'service.uzd.organs.p1': 'УЗИ позволяет выявить воспаления, новообразования, камни в желчном пузыре или почках на ранних этапах:',
    'service.uzd.organs.li1': '<strong>Органы брюшной полости:</strong> детальный осмотр печени, желчного пузыря, поджелудочной железы и селезенки.',
    'service.uzd.organs.li2': '<strong>Мочевыделительная система:</strong> почки, надпочечники, мочевой пузырь.',
    'service.uzd.organs.li3': '<strong>Эндокринная система:</strong> щитовидная железа.',
    'service.uzd.organs.li4': '<strong>Мягкие ткани и лимфоузлы:</strong> диагностика поверхностных структур и периферических лимфатических узлов.',
    'service.uzd.prep_ab.title': '3. Как правильно подготовиться к УЗИ брюшной полости?',
    'service.uzd.prep_ab.p1': 'Качество обследования брюшной полости зависит от количества газов в кишечнике (газ создает помехи для ультразвука). Поэтому подготовка крайне важна:',
    'service.uzd.prep_ab.li1': '<strong>За 2-3 дня до исследования:</strong> исключите продукты, усиливающие газообразование (бобовые, свежие овощи и фрукты, капусту, черный хлеб, молоко, сладкие газированные напитки).',
    'service.uzd.prep_ab.li2': 'При склонности к метеоризму по рекомендации врача в течение этих дней можно принимать ветрогонные препараты (например, симетикон / эспумизан).',
    'service.uzd.prep_ab.li3': '<strong>В день исследования:</strong> процедура проводится строго <strong>натощак</strong> (последний прием пищи — минимум за 6–8 часов). Перед процедурой не следует курить и жевать резинку.',
    'service.uzd.prep_ab.li4': 'Если обследование назначено на вторую половину дня, возможен легкий завтрак не позднее чем за 6 часов до процедуры, после чего есть запрещено.',
    'service.uzd.prep_ur.title': '4. Подготовка к УЗИ почек и мочевого пузыря',
    'service.uzd.prep_ur.p1': 'Для качественного осмотра стенок мочевого пузыря и прилегающих структур он должен быть хорошо заполнен:',
    'service.uzd.prep_ur.li1': 'Примерно за 1–1.5 часа до запланированного исследования выпейте 1 литр чистой негазированной воды или компота (без газа).',
    'service.uzd.prep_ur.li2': 'После этого не следует посещать туалет до завершения процедуры обследования.',
    'service.uzd.adv.title': '5. Какие преимущества УЗИ и когда оно необходимо?',
    'service.uzd.adv.p1': 'УЗИ является первичным инструментом скрининга благодаря скорости выполнения и высокой информативности. Врачи назначают его при болях в животе, нарушениях пищеварения, дискомфорте при мочеиспускании, появлении припухлостей в мягких тканях или отклонениях в лабораторных анализах.',
    'service.uzd.adv.p2': 'Исследование позволяет быстро установить предварительный диагноз и определить дальнейшую тактику обследования или терапии, не заставляя пациента ждать.',

    'service.surgery.meta.title': 'Хирургия и малоинвазивные вмешательства | Врач Тетерник О.А.',
    'service.surgery.title': 'Хирургия и малоинвазивные вмешательства',
    'service.surgery.subtitle': 'Современные хирургические методики и эндоскопические операции без традиционных разрезов.',
    'service.surgery.btn': 'Получить консультацию хирурга',
    'service.surgery.toc.title': 'Путеводитель по вопросам подготовки и проведения:',
    'service.surgery.toc.item1': '1. Что такое оперативная эндоскопия?',
    'service.surgery.toc.item2': '2. Какие операции выполняются эндоскопически?',
    'service.surgery.toc.item3': '3. Как проходит удаление полипов (полипэктомия)?',
    'service.surgery.toc.item4': '4. Как подготовиться к эндоскопической операции?',
    'service.surgery.toc.item5': '5. Преимущества и период восстановления',
    'service.surgery.about.title': '1. Что такое оперативная эндоскопия?',
    'service.surgery.about.p1': '<strong>Оперативная эндоскопия</strong> — это передовое направление малоинвазивной хирургии. Оно позволяет выполнять полноценные хирургические вмешательства внутри полых органов (пищевода, желудка, кишечника) через естественные пути с помощью гибких эндоскопов и специальных микроинструментов.',
    'service.surgery.about.p2': 'Главное отличие от классической хирургии — полное отсутствие разрезов на коже (брюшной стенки). Врач контролирует весь процесс на экране монитора с многократным оптическим увеличением, что гарантирует высокую точность и безопасность вмешательства.',
    'service.surgery.ops.title': '2. Какие операции выполняются эндоскопически?',
    'service.surgery.ops.p1': 'В современной эндоскопической практике выполняется широкий спектр лечебных процедур:',
    'service.surgery.ops.li1': '<strong>Полипэктомия:</strong> удаление доброкачественных образований (полипов) в желудке, двенадцатиперстной и толстой кишке для профилактики онкологии.',
    'service.surgery.ops.li2': '<strong>Остановка кровотечений:</strong> коагуляция сосудов или клипирование при острых желудочно-кишечных кровотечениях (например, при язве).',
    'service.surgery.ops.li3': '<strong>Удаление инородных тел:</strong> безопасное извлечение предметов, случайно попавших в пищевод или желудок.',
    'service.surgery.ops.li4': '<strong>Бужирование и расширение:</strong> восстановление проходимости суженных участков пищевода.',
    'service.surgery.poly.title': '3. Как проходит удаление полипов (полипэктомия)?',
    'service.surgery.poly.p1': 'Удаление полипов выполняется безболезненно во время диагностического осмотра (гастроскопии или колоноскопии) в состоянии <strong>медикаментозного сна (седации)</strong>.',
    'service.surgery.poly.p2': 'На ножку полипа набрасывается специальная металлическая петля, через которую пропускается ток высокой частоты. Полип срезается, а сосуд в его основании сразу коагулируется (прижигается), что предотвращает кровотечение. Все удаленные ткани обязательно направляются на <strong>гистологическое исследование</strong>.',
    'service.surgery.prep.title': '4. Как подготовиться к эндоскопической операции?',
    'service.surgery.prep.p1': 'Подготовка зависит от того, на каком органе будет выполняться операция, и осуществляется по тем же правилам, что и для диагностического осмотра:',
    'service.surgery.prep.li1': '<strong>Желудок (ВГДС-операции):</strong> строго натощак (не есть 6-8 часов, не пить жидкости за 2 часа до седации).',
    'service.surgery.prep.li2': '<strong>Толстый кишечник (КС-операции):</strong> соблюдение бесшлаковой диеты в течение 3 дней и полное очищение препаратом Изиклин по схеме.',
    'service.surgery.prep.li3': '<strong>Анализы:</strong> перед плановым хирургическим вмешательством необходимо сдать стандартный перечень анализов крови (клинический, коагулограмму, группу крови) и сделать ЭКГ.',
    'service.surgery.prep.li4': '<strong>Лекарства:</strong> если вы постоянно принимаете антикоагулянты (препараты, разжижающие кровь), обязательно обсудите это с хирургом заранее — некоторые из них необходимо временно отменить за несколько дней до операции.',
    'service.surgery.rec.title': '5. Преимущества и период восстановления',
    'service.surgery.rec.p1': 'Малоинвазивный характер операции обеспечивает отсутствие боли в послеоперационном периоде и быструю реабилитацию. Большинство пациентов отпускают домой уже через несколько часов после операции.',
    'service.surgery.rec.p2': 'Рекомендуется соблюдать щадящую диету и исключить тяжелые физические нагрузки, горячую ванну и баню в течение 5-7 дней после вмешательства.'
  },
  en: {
    'logo.main': 'Endoscopy',
    'logo.accent': 'in simple terms',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.diplomas': 'Diplomas',
    'nav.reviews': 'Reviews',
    'nav.contacts': 'Contacts',
    'nav.appointment': 'Book Appointment',
    'nav.blog': 'Blog',
    'nav.topics': 'Topics',
    'nav.ask': 'Ask a Question',
    'hero.badge.blog': 'Educational blog of Dr. Oleg Teternik',
    'hero.title.main': 'Endoscopy',
    'hero.title.accent': 'in simple terms',
    'hero.specialization': 'Explaining gastroscopy, colonoscopy, preparation, and treatment without myths and unnecessary fear. Advice from an endoscopist, surgeon, and ultrasound specialist with 8 years of experience.',
    'hero.experience.number': '8',
    'hero.experience.label': 'Years of professional\nexperience in medicine',
    'hero.btn.blog': 'Read Blog',
    'hero.btn.ask': 'Ask a Question',
    'hero.float.value': '5000+',
    'hero.float.label': 'Satisfied patients',
    'hero.scroll': 'Scroll down',
    'stats.exp.label': 'Years of Experience',
    'stats.exp.sub': 'in endoscopy & medicine',
    'stats.patients.label': 'Procedures per year',
    'stats.patients.sub': 'over 3000 examinations',
    'stats.patients.live': 'Annually',
    'stats.spec.number': 'Endoscopist',
    'stats.spec.label': 'Specialization',
    'stats.spec.sub': 'diagnostic & therapeutic endoscopy',
    'section.stats': 'Trust in Numbers',
    'section.about': 'About the Doctor',
    'section.services': 'Services',
    'section.diplomas': 'Diplomas & Certificates',
    'section.reviews': 'Patient Reviews',
    'section.contacts': 'Contacts',
    'about.subtitle': 'Meet the Doctor',
    'about.title': 'Teternik Oleg Oleksandrovych',
    'about.role': 'Surgeon Endoscopist',
    'about.bio.1': 'A professional with 8 years of experience in performing high-precision endoscopic and surgical interventions. The main priority is maximum safety, painlessness, and patient comfort during every procedure.',
    'about.bio.2': 'Thanks to modern equipment and an individual approach, we provide accurate diagnosis and effective treatment of gastrointestinal diseases.',
    'about.spec.1': 'Gastroscopy',
    'about.spec.2': 'Colonoscopy',
    'about.spec.3': 'ERCP',
    'about.spec.4': 'Bronchoscopy',
    'about.spec.5': 'Ultrasound',
    'about.spec.6': 'Surgery',
    'about.card.location.label': 'Location',
    'about.card.location.value': '17th Hospital, Kharkiv, Heroiv Kharkova Ave 195',
    'about.card.phone.label': 'Phone',
    'about.btn': 'Book Appointment',
    'services.subtitle': 'Fields & Diagnostics',
    'services.title': 'Medical Services',
    'services.card.btn': 'Learn More About Procedure',
    'services.modal.close': 'Close',
    'services.modal.appointment': 'Book Appointment',
    'services.modal.steps_title': 'Step-by-Step Procedure Process',
    'appointment.modal.title': 'Book an Appointment',
    'appointment.modal.subtitle': 'Fill out the form below or use our Telegram Bot',
    'appointment.form.name.label': 'Your Full Name',
    'appointment.form.name.placeholder': 'John Doe',
    'appointment.form.phone.label': 'Phone Number',
    'appointment.form.phone.placeholder': '+380XXXXXXXXX',
    'appointment.form.service.label': 'Select Service',
    'appointment.form.comment.label': 'Short comment / symptoms (optional)',
    'appointment.form.comment.placeholder': 'Describe your symptoms or preferred time...',
    'appointment.form.submit': 'Submit Appointment Request',
    'appointment.divider': 'or fill out the online form',
    'appointment.tg.btn': 'Book via Telegram Bot',
    'appointment.success.title': 'Thank You! Request Received',
    'appointment.success.desc': 'We will call you shortly to confirm your appointment time.',
    'appointment.success.btn': 'Got it',
    'contacts.subtitle': 'Location & Contacts',
    'contacts.title': 'Contact Information',
    'contacts.address.label': 'Location',
    'contacts.address.value': '17th City Hospital, Kharkiv, Heroiv Kharkova Ave 195',
    'contacts.schedule.label': 'Working Hours',
    'contacts.schedule.value': 'Mon – Sat: 08:00 – 15:00',
    'contacts.schedule.sub': 'Sunday: Closed',
    'contacts.phone.label': 'Phone Number',
    'contacts.instagram.label': 'Official Instagram',
    'contacts.navigation.title': 'How to find the Surgery Building?',
    'contacts.navigation.desc': 'Watch the step-by-step video guide in Instagram Highlight Stories',
    'contacts.navigation.btn': 'View Route',
    'contacts.map.btn': 'Open in Google Maps',
    'contacts.appointment.btn': 'Book Appointment',
    'reviews.subtitle': 'Trust & Real Experience',
    'reviews.title': 'Patient Reviews',
    'reviews.btn.leave': 'Leave a Review',
    'reviews.rating.count': 'based on patient ratings',
    'reviews.loading': 'Loading reviews...',
    'reviews.empty': 'No published reviews yet. Be the first to leave one!',
    'reviews.modal.title': 'Your Review of the Visit',
    'reviews.modal.subtitle': 'Share your impressions of the procedure or consultation',
    'reviews.modal.name.label': 'Your Full Name',
    'reviews.modal.name.placeholder': 'Jane Smith',
    'reviews.modal.stars.label': 'Your Rating',
    'reviews.modal.text.label': 'Review Text',
    'reviews.modal.text.placeholder': 'Write your feedback on the visit, doctor\'s attitude...',
    'reviews.modal.submit': 'Submit Review',
    'reviews.success.title': 'Thank You for Your Review!',
    'reviews.success.desc': 'Your review has been saved and will be published after moderation.',
    'exhibits.esge.city': 'Milan, Italy',
    'exhibits.esge.title': 'ESGE Days 2026',
    'exhibits.esge.desc': 'International Endoscopic Conference. Exchange of experience with leading European specialists, discussion of the latest standards and technologies in operative endoscopy.',
    'exhibits.kiev.city': 'Kyiv, Ukraine',
    'exhibits.kiev.title': 'KievEndo 2023',
    'exhibits.kiev.desc': 'Scientific and Practical Conference. Presentation of clinical cases, discussion of modern techniques of minimally invasive surgery and diagnostic endoscopy in Ukraine.',
    'footer.copy': '© 2026 Teternik O.O. All rights reserved.',
    'topics.more': 'Learn More',
    'topics.less': 'Collapse',
    'topics.gastro.label': 'Gastroscopy',
    'topics.gastro.sublabel': 'Preparation, procedure, results',
    'topics.gastro.q1': 'What is it?',
    'topics.gastro.a1': 'An examination of the lining of the esophagus, stomach, and duodenum using a flexible, thin scope with a video camera.',
    'topics.gastro.q2': 'When should you get one?',
    'topics.gastro.li1': 'Frequent heartburn, belching, bitterness in the mouth',
    'topics.gastro.li2': 'Pain in the upper abdomen (on an empty stomach or after eating)',
    'topics.gastro.li3': 'Persistent nausea or difficulty swallowing',
    'topics.gastro.q3': 'How to prepare?',
    'topics.gastro.a3': 'The procedure is performed strictly <strong>fasting</strong>. Last meal — at least 8-10 hours before the examination. Do not drink water 3-4 hours before the procedure.',
    'topics.gastro.btn': 'Details about Gastroscopy',
    'topics.gastro.posts_btn': 'Articles about Gastroscopy',
    'topics.colono.label': 'Colonoscopy',
    'topics.colono.sublabel': 'How to prepare and overcome fear',
    'topics.colono.q1': 'Why is it vital?',
    'topics.colono.a1': 'The gold standard for colon cancer prevention. Allows detecting and immediately removing polyps (benign growths) before they become dangerous.',
    'topics.colono.q2': 'Is it painful?',
    'topics.colono.a2': 'Modern colonoscopy is performed <strong>under sedation (medical sleep)</strong> in 95% of cases. You simply sleep for 15-20 minutes and do not feel any discomfort.',
    'topics.colono.q3': 'Key to preparation:',
    'topics.colono.a3': 'The quality of the exam is 90% dependent on bowel cleanliness. Follow a low-residue diet for 3 days and drink a special bowel-prep solution the night before.',
    'topics.colono.btn': 'Details about Colonoscopy',
    'topics.colono.posts_btn': 'Articles about Colonoscopy',
    'topics.usg.label': 'Ultrasound & Surgery',
    'topics.usg.sublabel': 'When and why you need them',
    'topics.usg.q1': 'Ultrasound Diagnostics',
    'topics.usg.a1': 'A quick and safe method to check the condition of internal organs (liver, gallbladder, pancreas, kidneys) without radiation.',
    'topics.usg.q2': 'Operative Endoscopy',
    'topics.usg.a2': 'This is surgery without incisions. With the endoscope, the doctor can remove foreign bodies, stop internal bleeding, or perform a polypectomy (removal of stomach or bowel polyps) during the examination.',
    'topics.usg.q3': 'Advantages:',
    'topics.usg.a3': 'The patient recovers within a few hours after the procedure and can return to normal life.',
    'topics.usg.btn1': 'Details about Ultrasound',
    'topics.usg.posts_btn1': 'Articles about Ultrasound',
    'topics.usg.btn2': 'Details about Surgery',
    'topics.usg.posts_btn2': 'Articles about Surgery',
    'blog.subtitle': 'Expert Materials',
    'blog.title': 'Blog about Endoscopy',
    'blog.desc': 'Endoscopist Dr. Oleg Teternik explains procedures, busts myths, and shares useful tips for endoscopy preparation.',
    'blog.empty': 'No posts published yet.',
    'diplomas.subtitle': 'Education & Achievements',
    'diplomas.title': 'Diplomas & Certificates',
    'diplomas.tab.education': 'Education',
    'diplomas.tab.certificates': 'Certificates',
    'diplomas.tab.exhibitions': 'Conferences & Exhibitions',

    // New keys for English service pages
    'service.back': 'Back to homepage',
    'appointment.form.btn_redirect': 'Fill out form on website',
'service.gastro.meta.title': 'Gastroscopy | Dr. Teternik O.O.',
    'service.gastro.title': 'Gastroscopy',
    'service.gastro.subtitle': 'Modern endoscopic examination of the stomach without fear, pain, and discomfort.',
    'service.gastro.btn': 'Book a Gastroscopy',
    'service.gastro.toc.title': 'Preparation & Procedure Guide:',
    'service.gastro.toc.item1': '1. Why is proper preparation important?',
    'service.gastro.toc.item2': '2. Recommendations 1 day before the exam',
    'service.gastro.toc.item3': '3. What to do on the day of gastroscopy?',
    'service.gastro.toc.item4': '4. If you constantly take medications',
    'service.gastro.toc.item5': '5. If gastroscopy is under sedation (medical sleep)',
    'service.gastro.toc.item6': '6. What to bring and how to dress?',
    'service.gastro.why.title': '1. Why is proper preparation important?',
    'service.gastro.why.p1': '<strong>Gastroscopy (EGD)</strong> is a precise method of examining the esophagus, stomach, and duodenum. For the doctor to perform a detailed inspection of the mucous membrane, and detect even tiny inflammations, ulcers, polyps, or early cancer, the stomach must be completely empty.',
    'service.gastro.why.p2': 'Even a small amount of food or fluid in the stomach can significantly impair the visibility of the mucous membrane, increase the risk of vomiting reflex during the procedure, and complicate accurate diagnosis.',
    'service.gastro.diet1.title': '2. Recommendations 1 day before the exam',
    'service.gastro.diet1.li1': 'Eat as usual, but avoid overeating and heavy foods.',
    'service.gastro.diet1.li2': 'Last light meal — no later than <strong>19:00–20:00</strong> (if the procedure is scheduled for the morning).',
    'service.gastro.diet1.li3': 'Do not consume alcohol under any circumstances the night before the procedure.',
    'service.gastro.day.title': '3. What to do on the day of gastroscopy?',
    'service.gastro.day.morning_title': 'If the procedure is in the morning:',
    'service.gastro.day.morning_li1': 'Do not eat for at least <strong>6–8 hours</strong> before the procedure.',
    'service.gastro.day.morning_li2': 'Do not drink milk, coffee, juices, or carbonated beverages.',
    'service.gastro.day.morning_li3': 'Clean non-carbonated water can be drunk in small sips no later than <strong>2 hours</strong> before the procedure.',
    'service.gastro.day.afternoon_title': 'If the procedure is in the afternoon:',
    'service.gastro.day.afternoon_p': 'A light breakfast is allowed no later than <strong>6–8 hours</strong> before the examination. Any further food intake after this is strictly forbidden.',
    'service.gastro.med.title': '4. If you constantly take medications',
    'service.gastro.med.li1': 'Medications for blood pressure and most heart conditions can be taken in the morning as usual, with a minimal amount of clean water.',
    'service.gastro.med.li2': 'If you take insulin, blood sugar-lowering drugs, or blood thinners (anticoagulants), be sure to inform your doctor in advance.',
    'service.gastro.med.li3': 'A temporary adjustment of the intake schedule or cancellation of some medications might be needed in agreement with the doctor.',
    'service.gastro.sedation.title': '5. If gastroscopy is under sedation (medical sleep)',
    'service.gastro.sedation.li1': 'Do not eat for at least <strong>6–8 hours</strong> before the procedure.',
    'service.gastro.sedation.li2': 'Do not drink any fluids for the last <strong>2 hours</strong> before the procedure.',
    'service.gastro.sedation.li3': 'Warning! After sedation, driving a car is strictly prohibited for 24 hours. Please arrange for someone to accompany you home in advance.',
    'service.gastro.before.title': '6. What to bring and how to dress?',
    'service.gastro.before.li1': 'Bring the results of previous gastroscopies, biopsies, and other medical examinations (if available) so the doctor can assess the dynamics.',
    'service.gastro.before.li2': 'If you wear removable dentures, they must be removed immediately before the examination.',
    'service.gastro.before.li3': 'Wear comfortable, loose clothing that does not compress the neck, chest, or abdomen.',

'service.colono.meta.title': 'Colonoscopy | Dr. Teternik O.O.',
    'service.colono.title': 'Colonoscopy (videocolonoscopy)',
    'service.colono.subtitle': 'Effective examination of the large intestine under medical sleep.',
    'service.colono.btn': 'Book a Colonoscopy',
    'service.colono.toc.title': 'Preparation & Procedure Guide:',
    'service.colono.toc.item1': '1. Why is colonoscopy vital and what is it?',
    'service.colono.toc.item2': '2. Low-residue diet 3 days before the exam',
    'service.colono.toc.item3': '3. What to eat and drink the day before?',
    'service.colono.toc.item4': '4. Eziclen intake schedule (split-dose)',
    'service.colono.toc.item5': '5. Important recommendations during preparation',
    'service.colono.toc.item6': '6. Video guide on preparation',
    'service.colono.why.title': '1. Why is colonoscopy vital and what is it?',
    'service.colono.why.p1': '<strong>Videocolonoscopy (CS)</strong> — is a highly precise endoscopic examination method that allows the doctor to inspect the lining of the large intestine in detail from the inside using a special flexible scope (colonoscope).',
    'service.colono.why.p2': 'A well-cleansed bowel allows the doctor to carefully inspect the mucous membrane, identify even tiny polyps or early forms of colon cancer and, if necessary, remove them immediately. Quality preparation significantly increases the accuracy of the colonoscopy and can eliminate the need for a repeat examination.',
    'service.colono.diet3.title': '2. Low-residue diet 3 days before the exam',
    'service.colono.diet3.p1': 'It is recommended to switch to a low-residue diet 3 days before the colonoscopy.',
    'service.colono.diet3.allowed_title': 'Allowed food and drinks:',
    'service.colono.diet3.allowed_li1': 'boiled meat and fish;',
    'service.colono.diet3.allowed_li2': 'eggs;',
    'service.colono.diet3.allowed_li3': 'white bread or toasts;',
    'service.colono.diet3.allowed_li4': 'rice, semolina porridge;',
    'service.colono.diet3.allowed_li5': 'plain dairy products without additives;',
    'service.colono.diet3.allowed_li6': 'clear broths.',
    'service.colono.diet3.forbidden_title': 'Forbidden food and drinks:',
    'service.colono.diet3.forbidden_li1': 'vegetables and fruits;',
    'service.colono.diet3.forbidden_li2': 'berries;',
    'service.colono.diet3.forbidden_li3': 'greens, mushrooms, nuts;',
    'service.colono.diet3.forbidden_li4': 'seeds, legumes;',
    'service.colono.diet3.forbidden_li5': 'black bread;',
    'service.colono.diet3.forbidden_li6': 'whole grain porridges.',
    'service.colono.diet1.title': '3. What to eat and drink the day before?',
    'service.colono.diet1.allowed_title': 'Only clear liquids are allowed:',
    'service.colono.diet1.allowed_li1': 'water, weak tea;',
    'service.colono.diet1.allowed_li2': 'clear broth;',
    'service.colono.diet1.allowed_li3': 'apple juice without pulp;',
    'service.colono.diet1.allowed_li4': 'clear sports drinks.',
    'service.colono.diet1.forbidden_p': 'Milk, kefir, juices with pulp, and alcohol are not allowed.',
    'service.colono.prep.title': '4. Eziclen intake schedule',
    'service.colono.prep.p1': 'The split-dose scheme of preparation provides the best result.',
    'service.colono.prep.morning_title': 'If colonoscopy is scheduled for the morning',
    'service.colono.prep.morning_li1': '<strong>The evening before (18:00–20:00):</strong> drink the first dose of Eziclen according to instructions, and then drink about 1 liter of clear liquid.',
    'service.colono.prep.morning_li2': '<strong>The morning of the examination (4–5 hours before the procedure):</strong> take the second dose of the drug, and then drink 1 liter of clear liquid again.',
    'service.colono.prep.morning_p': 'All liquids must be finished at least 2 hours before sedation or procedure (unless your doctor has given other recommendations).',
    'service.colono.prep.afternoon_title': 'If colonoscopy is scheduled for the afternoon',
    'service.colono.prep.afternoon_p': 'The first dose can be taken in the morning, and the second one a few hours later, following the detailed recommendations of your doctor.',
    'service.colono.tips.title': '5. Important recommendations during preparation',
    'service.colono.tips.li1': 'Drink enough fluids during preparation to avoid dehydration.',
    'service.colono.tips.li2': 'If you constantly take blood thinners, blood sugar-lowering drugs, or insulin, be sure to inform your doctor in advance.',
    'service.colono.tips.li3': 'In case of severe nausea or vomiting, contact medical staff.',
    'service.colono.video.title': '6. Video guide on preparation',
    'service.colono.video.desc': 'Watch a detailed video on how to correctly prepare for the endoscopic examination:',

'service.uzd.meta.title': 'Ultrasound Diagnostics | Dr. Teternik O.O.',
    'service.uzd.title': 'Ultrasound Diagnostics (USG)',
    'service.uzd.subtitle': 'Safe, painless, and accurate method of evaluating internal organs.',
    'service.uzd.btn': 'Book an Ultrasound',
    'service.uzd.toc.title': 'Preparation & Procedure Guide:',
    'service.uzd.toc.item1': '1. What is ultrasound and how does it work?',
    'service.uzd.toc.item2': '2. What organs can be examined with ultrasound?',
    'service.uzd.toc.item3': '3. How to properly prepare for an abdominal ultrasound?',
    'service.uzd.toc.item4': '4. Preparation for kidney and bladder ultrasound',
    'service.uzd.toc.item5': '5. What are the benefits of ultrasound and when is it needed?',
    'service.uzd.about.title': '1. What is ultrasound and how does it work?',
    'service.uzd.about.p1': '<strong>Ultrasound Diagnostics (USG)</strong> is a non-invasive, quick, and completely safe examination method. It is based on the use of high-frequency sound waves that reflect from body tissues and form a clear image of internal organs on the scanner screen in real time.',
    'service.uzd.about.p2': 'Since ultrasound does not use ionizing (X-ray) radiation, it is absolutely harmless. The examination can be performed multiple times on patients of any age, including children and pregnant women, to assess the shape, size, structure of organs, and blood flow in them.',
    'service.uzd.organs.title': '2. What organs can be examined with ultrasound?',
    'service.uzd.organs.p1': 'Ultrasound allows detecting inflammation, tumors, stones in the gallbladder or kidneys at early stages:',
    'service.uzd.organs.li1': '<strong>Abdominal organs:</strong> detailed view of liver, gallbladder, pancreas, and spleen.',
    'service.uzd.organs.li2': '<strong>Urinary system:</strong> kidneys, adrenal glands, urinary bladder.',
    'service.uzd.organs.li3': '<strong>Endocrine system:</strong> thyroid gland.',
    'service.uzd.organs.li4': '<strong>Soft tissues and lymph nodes:</strong> diagnostics of superficial structures and peripheral lymph nodes.',
    'service.uzd.prep_ab.title': '3. How to properly prepare for an abdominal ultrasound?',
    'service.uzd.prep_ab.p1': 'The quality of the abdominal examination depends on the amount of gas in the bowel (gas interferes with ultrasound). Therefore, preparation is extremely important:',
    'service.uzd.prep_ab.li1': '<strong>2-3 days before the examination:</strong> exclude foods that increase gas production (legumes, fresh vegetables and fruits, cabbage, black bread, milk, sweet carbonated drinks).',
    'service.uzd.prep_ab.li2': 'If prone to flatulence, carminative drugs (e.g., simethicone / espumisan) can be taken during these days upon doctor\'s recommendation.',
    'service.uzd.prep_ab.li3': '<strong>On the day of the examination:</strong> the procedure is performed strictly <strong>fasting</strong> (last meal — at least 6–8 hours). Do not smoke or chew gum before the procedure.',
    'service.uzd.prep_ab.li4': 'If the examination is scheduled for the afternoon, a light breakfast is allowed no later than 6 hours before the procedure, after which eating is forbidden.',
    'service.uzd.prep_ur.title': '4. Preparation for kidney and bladder ultrasound',
    'service.uzd.prep_ur.p1': 'For a high-quality view of the bladder walls and adjacent structures, it must be well filled:',
    'service.uzd.prep_ur.li1': 'Approximately 1–1.5 hours before the scheduled examination, drink 1 liter of clean non-carbonated water or compote.',
    'service.uzd.prep_ur.li2': 'After that, do not visit the restroom until the examination procedure is completed.',
    'service.uzd.adv.title': '5. What are the benefits of ultrasound and when is it needed?',
    'service.uzd.adv.p1': 'Ultrasound is a primary screening tool due to its speed and high information value. Doctors prescribe it for abdominal pain, digestive disorders, discomfort during urination, swelling in soft tissues, or deviations in laboratory tests.',
    'service.uzd.adv.p2': 'The examination allows quickly establishing a preliminary diagnosis and determining further tactics of examination or therapy, without making the patient wait.',

    'service.surgery.meta.title': 'Surgery & Minimally Invasive Interventions | Dr. Teternik O.O.',
    'service.surgery.title': 'Surgery & Minimally Invasive Interventions',
    'service.surgery.subtitle': 'Modern surgical techniques and endoscopic procedures without traditional incisions.',
    'service.surgery.btn': 'Get consultation from surgeon',
    'service.surgery.toc.title': 'Preparation & Procedure Guide:',
    'service.surgery.toc.item1': '1. What is operative endoscopy?',
    'service.surgery.toc.item2': '2. What operations are performed endoscopically?',
    'service.surgery.toc.item3': '3. How is polyp removal (polypectomy) performed?',
    'service.surgery.toc.item4': '4. How to prepare for an endoscopic surgery?',
    'service.surgery.toc.item5': '5. Advantages and recovery period',
    'service.surgery.about.title': '1. What is operative endoscopy?',
    'service.surgery.about.p1': '<strong>Operative Endoscopy</strong> is an advanced field of minimally invasive surgery. It allows full surgical interventions inside hollow organs (esophagus, stomach, intestines) through natural pathways using flexible endoscopes and special micro-instruments.',
    'service.surgery.about.p2': 'The main difference from classic surgery is the complete absence of incisions on the skin (abdominal wall). The doctor controls the entire process on the monitor screen with multiple optical magnification, which guarantees high precision and safety of the intervention.',
    'service.surgery.ops.title': '2. What operations are performed endoscopically?',
    'service.surgery.ops.p1': 'In modern endoscopic practice, a wide range of therapeutic procedures is performed:',
    'service.surgery.ops.li1': '<strong>Polypectomy:</strong> removal of benign formations (polyps) in the stomach, duodenum, and colon for cancer prevention.',
    'service.surgery.ops.li2': '<strong>Hemostasis:</strong> coagulation of blood vessels or clipping in acute gastrointestinal bleeding (e.g., with ulcers).',
    'service.surgery.ops.li3': '<strong>Removal of foreign bodies:</strong> safe extraction of objects accidentally ingested into the esophagus or stomach.',
    'service.surgery.ops.li4': '<strong>Dilation and bougienage:</strong> restoring patency of narrowed sections of the esophagus.',
    'service.surgery.poly.title': '3. How is polyp removal (polypectomy) performed?',
    'service.surgery.poly.p1': 'Polyp removal is performed painlessly during diagnostic examination (gastroscopy or colonoscopy) under <strong>sedation (medical sleep)</strong>.',
    'service.surgery.poly.p2': 'A special metal snare is placed over the polyp stalk, through which a high-frequency current is passed. The polyp is cut off, and the vessel at its base is immediately coagulated (cauterized), which prevents bleeding. All removed tissues must be sent for <strong>histological examination</strong>.',
    'service.surgery.prep.title': '4. How to prepare for an endoscopic surgery?',
    'service.surgery.prep.p1': 'Preparation depends on the organ being operated on and is carried out according to the same rules as for diagnostic examination:',
    'service.surgery.prep.li1': '<strong>Stomach (EGD procedures):</strong> strictly fasting (no food for 6-8 hours, no fluids 2 hours before sedation).',
    'service.surgery.prep.li2': '<strong>Large intestine (CS procedures):</strong> low-residue diet for 3 days and complete cleansing with Eziclen according to the schedule.',
    'service.surgery.prep.li3': '<strong>Tests:</strong> before a planned surgical intervention, it is necessary to pass a standard list of blood tests (complete blood count, coagulogram, blood type) and do an ECG.',
    'service.surgery.prep.li4': '<strong>Medications:</strong> if you constantly take anticoagulants (blood thinners), be sure to discuss this with the surgeon in advance — some of them must be temporarily stopped a few days before the surgery.',
    'service.surgery.rec.title': '5. Advantages and recovery period',
    'service.surgery.rec.p1': 'The minimally invasive nature of the operation ensures no pain in the postoperative period and rapid rehabilitation. Most patients are discharged home within a few hours after the procedure.',
    'service.surgery.rec.p2': 'It is recommended to follow a gentle diet and exclude heavy physical exertion, hot baths, and saunas for 5-7 days after the intervention.'
  }
};

const html = fs.readFileSync('index.html', 'utf8');

// Compile page with translations
function compilePage(sourceHtml, langCode) {
    const $ = cheerio.load(sourceHtml, { decodeEntities: false });
    const langData = translations[langCode];

    if (langData) {
        $('[data-i18n]').each(function() {
            const key = $(this).attr('data-i18n');
            if (langData[key]) {
                const children = $(this).children('svg, img, .hero__badge-dot');
                if (children.length > 0) {
                   let textNodeReplaced = false;
                   $(this).contents().each(function() {
                      if (this.nodeType === 3 && this.nodeValue.trim() !== '' && !textNodeReplaced) {
                          this.nodeValue = this.nodeValue.replace(/[\s\S]+/, langData[key]);
                          textNodeReplaced = true;
                      }
                   });
                } else {
                   $(this).html(langData[key]);
                }
            }
        });
    }

    // Set HTML lang attribute
    $('html').attr('lang', langCode);

    return $;
}

// Generate translations for Main Landing Page
function generateMainLangs() {
    // RU main page
    const $ru = compilePage(html, 'ru');
    $ru('.lang-switch__btn').removeClass('active');
    $ru('a.lang-switch__btn:contains("RU")').addClass('active');
    $ru('title').text('Врач Тетерник О. А. — Эндоскопист, Хирург, УЗИ | Отзывы');
    $ru('meta[property="og:title"]').attr('content', 'Врач Тетерник О. А. — Эндоскопист, Хирург, УЗИ | Отзывы');
    $ru('meta[name="description"]').attr('content', 'Тетерник Олег Александрович — врач-эндоскопист, хирург, УЗИ. Отзывы пациентов. Эндоскопия в Харькове.');
    
    // Redirect internal links to localized routes in RU main page
    localizeLinks($ru, 'ru');
    fs.writeFileSync('ru.html', $ru.html());
    console.log('Generated ru.html');

    // EN main page
    const $en = compilePage(html, 'en');
    $en('.lang-switch__btn').removeClass('active');
    $en('a.lang-switch__btn:contains("EN")').addClass('active');
    $en('title').text('Dr. Teternik O. O. — Endoscopist, Surgeon, Ultrasound | Reviews');
    $en('meta[property="og:title"]').attr('content', 'Dr. Teternik O. O. — Endoscopist, Surgeon, Ultrasound | Reviews');
    $en('meta[name="description"]').attr('content', 'Teternik Oleg Oleksandrovych — Endoscopist, Surgeon, Ultrasound. Patient reviews. Endoscopy in Kharkiv.');
    
    // Redirect internal links to localized routes in EN main page
    localizeLinks($en, 'en');
    fs.writeFileSync('en.html', $en.html());
    console.log('Generated en.html');
}

// Localize subpage links for translated pages
function localizeLinks($, langCode) {
    const pages = ['gastroscopy', 'colonoscopy', 'uzd', 'surgery'];
    pages.forEach(p => {
        $(`a[href^="/${p}/"]`).not('.lang-switch a').each(function() {
            $(this).attr('href', `/${langCode}/${p}/`);
        });
    });
}

// Generate subpages (Gastroscopy, Colonoscopy, UZD, Surgery)
function generateSubpages() {
    const subpages = ['gastroscopy', 'colonoscopy', 'uzd', 'surgery'];

    subpages.forEach(page => {
        const pageHtmlPath = `${page}.html`;
        if (!fs.existsSync(pageHtmlPath)) {
            console.warn(`Source page not found: ${pageHtmlPath}`);
            return;
        }

        const baseHtml = fs.readFileSync(pageHtmlPath, 'utf8');

        // 1. Generate UA (default) subpage: /page/index.html
        fs.mkdirSync(path.join(__dirname, page), { recursive: true });
        const $ua = cheerio.load(baseHtml, { decodeEntities: false });
        fs.writeFileSync(path.join(__dirname, page, 'index.html'), $ua.html());
        console.log(`Generated UA subpage: /${page}/index.html`);

        // 2. Generate RU subpage: /ru/page/index.html
        fs.mkdirSync(path.join(__dirname, 'ru', page), { recursive: true });
        const $ru = compilePage(baseHtml, 'ru');
        $ru('.lang-switch__btn').removeClass('active');
        $ru(`.lang-switch a[href^="/ru/${page}/"]`).addClass('active');
        localizeLinks($ru, 'ru');
        fs.writeFileSync(path.join(__dirname, 'ru', page, 'index.html'), $ru.html());
        console.log(`Generated RU subpage: /ru/${page}/index.html`);

        // 3. Generate EN subpage: /en/page/index.html
        fs.mkdirSync(path.join(__dirname, 'en', page), { recursive: true });
        const $en = compilePage(baseHtml, 'en');
        $en('.lang-switch__btn').removeClass('active');
        $en(`.lang-switch a[href^="/en/${page}/"]`).addClass('active');
        localizeLinks($en, 'en');
        fs.writeFileSync(path.join(__dirname, 'en', page, 'index.html'), $en.html());
        console.log(`Generated EN subpage: /en/${page}/index.html`);
    });
}

// Build all
generateMainLangs();
generateSubpages();
